# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Tran - Software Developer
email: tran82h@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the new blog site of The Tran.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ITNinjaa
github_username:  tran82h
permalink: pretty
# Build settings
markdown: kramdown
kramdown:
  input: GFM
